<a href="https://colab.research.google.com/github/zeynepmerve97/Machine_Learning_Algorithms/blob/main/NaiveBayes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
#load libraries
import pandas as pd
import numpy as np
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import cross_val_score,train_test_split
from sklearn.datasets import load_wine
from sklearn.metrics import confusion_matrix, classification_report

In [11]:
#load dataset
wine = load_wine()
df = pd.DataFrame(np.c_[wine['data'], wine['target']],
                  columns = np.append(wine['feature_names'], ['target']))

In [12]:
X =  df.drop('target' ,axis = 1)
y = df['target']
print(X.head())
print(y.head())

   alcohol  malic_acid   ash  ...   hue  od280/od315_of_diluted_wines  proline
0    14.23        1.71  2.43  ...  1.04                          3.92   1065.0
1    13.20        1.78  2.14  ...  1.05                          3.40   1050.0
2    13.16        2.36  2.67  ...  1.03                          3.17   1185.0
3    14.37        1.95  2.50  ...  0.86                          3.45   1480.0
4    13.24        2.59  2.87  ...  1.04                          2.93    735.0

[5 rows x 13 columns]
0    0.0
1    0.0
2    0.0
3    0.0
4    0.0
Name: target, dtype: float64


In [16]:
#split dataset: train and test
X_train,X_test,y_train,y_test =train_test_split(X,y,test_size =0.2)

In [17]:
model = GaussianNB()
model.fit(X_train,y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [18]:
y_pred = model.predict(X_test)
y_pred

array([1., 0., 2., 2., 2., 0., 0., 2., 0., 0., 1., 0., 0., 1., 1., 0., 0.,
       2., 1., 0., 2., 0., 2., 0., 1., 2., 1., 1., 0., 1., 1., 1., 0., 2.,
       1., 0.])

In [20]:
scoring = cross_val_score(model,X_train,y_train,cv=2,scoring ='neg_mean_absolute_error')
print(scoring)

[-0.05633803 -0.        ]


In [22]:
cm = confusion_matrix(y_test,y_pred)
print(cm)

[[15  0  0]
 [ 0 12  0]
 [ 0  0  9]]


In [23]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00        15
         1.0       1.00      1.00      1.00        12
         2.0       1.00      1.00      1.00         9

    accuracy                           1.00        36
   macro avg       1.00      1.00      1.00        36
weighted avg       1.00      1.00      1.00        36

