<a href="https://colab.research.google.com/github/zeynepmerve97/Machine_Learning_Algorithms/blob/main/SVM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.datasets import load_iris, load_boston,load_diabetes

In [ ]:
iris_data = load_iris()
df = pd.DataFrame(iris_data.data)
print(df.head())
print(df.shape)
X = pd.DataFrame(iris_data.data, columns =iris_data.feature_names)
y = iris_data.target


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20)

     0    1    2    3
0  5.1  3.5  1.4  0.2
1  4.9  3.0  1.4  0.2
2  4.7  3.2  1.3  0.2
3  4.6  3.1  1.5  0.2
4  5.0  3.6  1.4  0.2
(150, 4)


In [ ]:
svclassifier = SVC(kernel='poly', degree=8)
svclassifier.fit(X_train, y_train)

y_pred = svclassifier.predict(X_test)

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[ 8  0  0]
 [ 0  8  0]
 [ 0  2 12]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         8
           1       0.80      1.00      0.89         8
           2       1.00      0.86      0.92        14

    accuracy                           0.93        30
   macro avg       0.93      0.95      0.94        30
weighted avg       0.95      0.93      0.93        30



In [ ]:
svclassifier = SVC(kernel='rbf')
svclassifier.fit(X_train, y_train)

y_pred = svclassifier.predict(X_test)

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[ 8  0  0]
 [ 0  8  0]
 [ 0  3 11]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         8
           1       0.73      1.00      0.84         8
           2       1.00      0.79      0.88        14

    accuracy                           0.90        30
   macro avg       0.91      0.93      0.91        30
weighted avg       0.93      0.90      0.90        30



In [ ]:
svclassifier = SVC(kernel='sigmoid')
svclassifier.fit(X_train, y_train)

y_pred = svclassifier.predict(X_test)

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[ 4  4  0]
 [ 6  2  0]
 [13  1  0]]
              precision    recall  f1-score   support

           0       0.17      0.50      0.26         8
           1       0.29      0.25      0.27         8
           2       0.00      0.00      0.00        14

    accuracy                           0.20        30
   macro avg       0.15      0.25      0.17        30
weighted avg       0.12      0.20      0.14        30



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
diabetes = load_diabetes()
df = pd.DataFrame(diabetes.data)
print(df.head())
print(df.shape)
X_diabetes = pd.DataFrame(diabetes.data, columns =diabetes.feature_names)
y_diabetes= diabetes.target


X_train_diabetes, X_test_diabetes, y_train_diabetes, y_test_diabetes = train_test_split(X_diabetes, y_diabetes, test_size = 0.20)

          0         1         2  ...         7         8         9
0  0.038076  0.050680  0.061696  ... -0.002592  0.019908 -0.017646
1 -0.001882 -0.044642 -0.051474  ... -0.039493 -0.068330 -0.092204
2  0.085299  0.050680  0.044451  ... -0.002592  0.002864 -0.025930
3 -0.089063 -0.044642 -0.011595  ...  0.034309  0.022692 -0.009362
4  0.005383 -0.044642 -0.036385  ... -0.002592 -0.031991 -0.046641

[5 rows x 10 columns]
(442, 10)


In [ ]:
svclassifier = SVC(kernel='poly', degree=8)
svclassifier.fit(X_train_diabetes, y_train_diabetes)

y_pred_diabetes= svclassifier.predict(X_test_diabetes)

print(confusion_matrix(y_test_diabetes, y_pred_diabetes))
print(classification_report(y_test_diabetes, y_pred_diabetes))

print(confusion_matrix(y_test_diabetes, y_pred_diabetes))
print(classification_report(y_test_diabetes,y_pred_diabetes))

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 1 0]]
              precision    recall  f1-score   support

        37.0       0.00      0.00      0.00       0.0
        40.0       0.00      0.00      0.00       0.0
        42.0       0.00      0.00      0.00       1.0
        52.0       0.00      0.00      0.00       1.0
        53.0       0.00      0.00      0.00       0.0
        59.0       0.00      0.00      0.00       1.0
        60.0       0.00      0.00      0.00       1.0
        63.0       0.00      0.00      0.00       1.0
        64.0       0.00      0.00      0.00       1.0
        67.0       0.00      0.00      0.00       1.0
        69.0       0.00      0.00      0.00       1.0
        70.0       0.00      0.00      0.00       2.0
        71.0       0.00      0.00      0.00       1.0
        72.0       0.00      0.00      0.00       1.0
        73.0       0.00      0.00      0.00       1.0
        74.0   

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
svclassifier = SVC(kernel='rbf')
from sklearn import preprocessing
lab_enc = preprocessing.LabelEncoder()
training_scores_encoded = lab_enc.fit_transform(y_train_boston)
svclassifier.fit(X_train_boston, training_scores_encoded )

y_pred_boston2 = svclassifier.predict(X_test_boston)

print(confusion_matrix(y_test_boston, y_pred_boston2))
print(classification_report(y_test_boston, y_pred_boston2))

ValueError: ignored

In [ ]:
svclassifier = SVC(kernel='sigmoid')
svclassifier.fit(X_train, y_train)

y_pred = svclassifier.predict(X_test)

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))